### PR TITLE
Bump Thoth's s2i base image

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
It looks like our CI fails to install dependencies - e.g. https://github.com/thoth-station/invectio/pull/72#issuecomment-598682868 Seems to be caused by old image, I cannot reproduce the issue with newer ones.

**Comment by harshad16** [comment]
@fridex thanks for taking care of upgrading the versions. 
can you include this one to here 
https://github.com/thoth-station/zuul-infra/blob/3e7ba8cd2e8543373e37f79940a6987974a802cb/thoth-pytest-f31-py37/Dockerfile#L1

**Comment by fridex** [comment]
> @fridex thanks for taking care of upgrading the versions.
> can you include this one to here
> https://github.com/thoth-station/zuul-infra/blob/3e7ba8cd2e8543373e37f79940a6987974a802cb/thoth-pytest-f31-py37/Dockerfile#L1

Sure, updated. Thanks for spotting it and sorry for missing it.

**Comment by harshad16** [comment]
> > @fridex thanks for taking care of upgrading the versions.
> > can you include this one to here
> > https://github.com/thoth-station/zuul-infra/blob/3e7ba8cd2e8543373e37f79940a6987974a802cb/thoth-pytest-f31-py37/Dockerfile#L1
> 
> Sure, updated. Thanks for spotting it and sorry for missing it.

you spotted the changes in the s2i-thoth, so thank you. :)

**Review by harshad16 — APPROVED** [review]

**Pull request merged**
